codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%
    patch:
      default:
        target: 100%
        threshold: 1%

comment: # this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false # learn more in the Requiring Changes section below
  require_base: false # [true :: must have a base report to post]
  require_head: false # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff]
