codecov:
  # notify PR with this commit status and flags
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: true
  require_base: no
  require_head: no
